main: me.screescree.SuperiorSteed.SuperiorSteed
name: SuperiorSteed
description: This plugin makes horses much more powerful, to make them more pet-like.
version: 1.0
author: screescree
api-version: 1.18

commands:
  horsestats:
    description: "Displays the stats of the horse you are currently riding or looking at."
    usage: "§cUsage: /<command>"
    permission: "superiorsteed.horsestats"
  horseperms:
    description: "Add, remove, and list players who can ride your horses."
    usage: "§cUsage: /<command> <add|remove> <player> §7OR §c/<command> <list> [page]"
    permission: "superiorsteed.horseperms"

  # admin commands
  summonhorse:
    description: "Displays a GUI to summon a custom horse."
    usage: "§cUsage: /<command>" 
    permission: "superiorsteed.admin.summonhorse"
  updatehorse:
    description: "Displays a GUI to modify the horse you are currently riding or looking at."
    usage: "§cUsage: /<command>"
    permission: "superiorsteed.admin.updatehorse"
  geld:
    description: "Gelds the stallion you are currently riding or looking at."
    usage: "§cUsage: /<command>"
    permission: "superiorsteed.geld"

  # debug commands
  horsecache:
    description: "Displays the cache of all horses in the server."
    usage: "§cUsage: /<command>"
    permission: "superiorsteed.debug.horsecache"
  readpersistentdata:
    description: "Displays the persistent data of the horse you are currently riding or looking at."
    usage: "§cUsage: /<command> <type> <key>"
    permission: "superiorsteed.debug.readpersistentdata"
  horsejumpandspeedtest:
    description: "Spawns a horse with a set jump strength and movement speed. (Probably doesn't even work anymore)"
    usage: "§cUsage: /<command> <jump_strength> <movement_speed>"
    permission: "superiorsteed.debug.horsejumpandspeedtest"

permissions:
  superiorsteed.horsestats:
    description: "Allows the user to see the stats of horses."
    default: true
  superiorsteed.horseperms:
    description: "Allows the player to add, remove, and list players who can ride their horses."
    default: true

  superiorsteed.admin:
    description: "Allows the user to use the plugin's admin commands."
    default: op
    children:
      superiorsteed.admin.rideallhorses: true
      superiorsteed.admin.summonhorse: true
      superiorsteed.admin.updatehorse: true
      superiorsteed.admin.geld: true
  superiorsteed.admin.rideallhorses:
    description: "Allows the user to ride all horses, regardless of the owner's permission."
    default: op
  superiorsteed.admin.summonhorse:
    description: "Allows the user to summon in a custom horse."
    default: op
  superiorsteed.admin.updatehorse:
    description: "Allows the user to set information about a horse."
    default: op
  superiorsteed.geld:
    description: "Allows the user to geld horses."
    default: op
  
  superiorsteed.debug:
    description: "Allows the user to use the plugin's debug commands."
    default: false
    children:
      superiorsteed.debug.horsecache: true
      superiorsteed.debug.readpersistentdata: true
      superiorsteed.debug.horsejumpandspeedtest: true
  superiorsteed.debug.horsecache:
    description: "Allows the user to see the cache of all horses in the server."
    default: false
  superiorsteed.debug.readpersistentdata:
    description: "Allows the user to read the persistent data of a horse."
    default: false
  superiorsteed.debug.horsejumpandspeedtest:
    description: "Allows the user to spawn a horse with a set jump strength and movement speed."
    default: false