main: me.screescree.SuperiorSteed.SuperiorSteed
name: SuperiorSteed
description: This plugin makes horses much more powerful, to make them more pet-like.
version: 1.0
author: screescree
api-version: 1.18

commands:
  horsestats:
    description: "Displays the stats of the horse you are currently riding or looking at."
    usage: "§cUsage: /<command>"
    permission: "superiorsteed.horsestats"
  # admin commands
  summonhorse:
    description: "Displays a GUI to summon a custom horse."
    usage: "§cUsage: /<command>" 
    permission: "superiorsteed.admin.summonhorse"
  updatehorse:
    description: "Displays a GUI to modify the horse you are currently riding or looking at."
    usage: "§cUsage: /<command>"
    permission: "superiorsteed.admin.updatehorse"

  # debug commands
  horsecache:
    description: "Displays the cache of all horses in the server."
    usage: "§cUsage: /<command>"
    permission: "superiorsteed.debug.horsecache"
  readpersistentdata:
    description: "Displays the persistent data of the horse you are currently riding or looking at."
    usage: "§cUsage: /<command> <type> <key>"
    permission: "superiorsteed.debug.readpersistentdata"

permissions:
  superiorsteed.horsestats:
    description: "Allows the user to see the stats of the horse they are looking at."
    default: true

  superiorsteed.admin:
    description: "Allows the user to use the plugin's admin commands."
    default: op
    children:
      superiorsteed.admin.summonhorse: true
  superiorsteed.admin.summonhorse:
    description: "Allows the user to summon in a custom horse."
    default: op
  superiorsteed.admin.sethorsestats:
    description: "Allows the user to set information about a horse."
    default: op
  
  superiorsteed.debug:
    description: "Allows the user to use the plugin's debug commands."
    default: false
    children:
      superiorsteed.debug.horsecache: true
      superiorsteed.debug.readpersistentdata: true
  superiorsteed.debug.horsecache:
    description: "Allows the user to see the cache of all horses in the server."
    default: false
  superiorsteed.debug.readpersistentdata:
    description: "Allows the user to read the persistent data of a horse."
    default: false